#!/bin/bash
set -euo pipefail

mkdir -p "$(dirname "$0")/lfs-tmp-sys/tools"

for script in "$(dirname "$0")/build-lfs-tmp-sys.d/"*; do
    exec 11<<EOH
lfs:x:$(id -u):$(id -g):lfs,,,:/tmp:/bin/bash
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
EOH

    exec 12<<EOH
lfs:x:$(id -g):
nogroup:x:65534:
EOH

    exec 13<<EOH
#!/bin/bash
umask 022
export HOME=/tmp
export TERM=$TERM
export LFS=/mnt/lfs
export LC_ALL=POSIX
export LFS_TGT=$(uname -m)-lfs-linux-gnu
export PATH=/tools/bin:/bin/:/usr/bin
export MAKEFLAGS=-j$(($(nproc) + 1))

if ! bash '/tmp/$(basename "$script")'; then
    echo "build failed. dropping to a shell." >&2
    PS1='\\u@\\h:\\w\\\$ ' bash --norc
    exit 1
fi
EOH

    bwrap \
          --ro-bind /usr /usr \
          --dir /tmp \
          --dir /var \
          --symlink ../tmp var/tmp \
          --proc /proc \
          --dev /dev \
          --ro-bind /etc/resolv.conf /etc/resolv.conf \
          --ro-bind /etc/ssl /etc/ssl \
          --bind /lib /lib \
          --bind /lib64 /lib64 \
          --bind /bin /bin \
          --unshare-all \
          --share-net \
          --die-with-parent \
          --hostname lfs-temporary-system-builder \
          --chdir /tmp \
          --file 11 /etc/passwd \
          --file 12 /etc/group \
          --bind "$(dirname "$0")/lfs-sources" /sources \
          --bind "$(dirname "$0")/lfs-tmp-sys" /mnt/lfs \
          --symlink mnt/lfs/tools /tools \
          --ro-bind "$script" "/tmp/$(basename "$script")" \
          --file 13 /build.sh \
          env -i /bin/bash /build.sh
done
