= Linux from Scratch
:source-highlighter: pygments
Kazutoshi Noguchi

== Installing Basic System Software
=== Gzip-1.9
Extract source code:
[source,bash]
----
cd /var/tmp
tar -xf /sources/gzip-1.9.tar.xz
cd gzip-1.9
----

Make some fixes required by glibc-2.28:

[source,bash]
----
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
----


Prepare Gzip for compilation:

[source,bash]
----
./configure --prefix=/usr
----

Compile the package:

[source,bash]
----
make
----

To test the results, issue:

[source,bash]
----
make check
----

Two tests are known to fail in the LFS environment: help-version and zmore.

Package gzip:

[source,bash]
----
make DESTDIR=/usr/pkg/gzip-1.9 install
----

Purging unneeded files:
[source,bash]
----
rm -fv /usr/pkg/gzip-1.9/usr/share/info/dir
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/gzip-1.9
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/gzip-1.9
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/gzip-1.9/* /
----

=== IPRoute2-4.18.0
Extract source code:
[source,bash]
----
cd /var/tmp
tar -xf /sources/iproute2-4.18.0.tar.xz
cd iproute2-4.18.0
----

The `arpd` program included in this package will not be built since it is dependent on Berkeley DB, which is not installed in LFS. However, a directory for `arpd` and a man page will still be installed. Prevent this by running the commands below. If the `arpd` binary is needed, instructions for compiling Berkeley DB can be found in the BLFS Book.

[source,bash]
----
sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8
----

It is also necessary to disable building two modules that requires iptables.

[source,bash]
----
sed -i 's/.m_ipt.o//' tc/Makefile
----

Compile the package:

[source,bash]
----
make
----

This package does not have a working test suite.

Install the package:

[source,bash]
----
make SBINDIR=/usr/bin DESTDIR=/usr/pkg/iproute2-4.18.0 install
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/iproute2-4.18.0
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/iproute2-4.18.0
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/iproute2-4.18.0/* /
----

=== Kbd-2.0.4
Extract source code:
[source,bash]
----
cd /var/tmp
tar -xf /sources/kbd-2.0.4.tar.xz
cd kbd-2.0.4
----

The behaviour of the Backspace and Delete keys is not consistent across the keymaps in the Kbd package. The following patch fixes this issue for i386 keymaps:

[source,bash]
----
patch -Np1 -i /sources/kbd-2.0.4-backspace-1.patch
----

After patching, the Backspace key generates the character with code 127, and the Delete key generates a well-known escape sequence.

Remove the redundant `resizecons` program (it requires the defunct svgalib to provide the video mode files - for normal use `setfont` sizes the console appropriately) together with its manpage.

[source,bash]
----
sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
----

Prepare Kbd for compilation:

[source,bash]
----
PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr --disable-vlock
----

.The meaning of the configure options:

--disable-vlock::
This option prevents the vlock utility from being built, as it requires the PAM library, which isn't available in the chroot environment.

Compile the package:

[source,bash]
----
make
----

To test the results, issue:

[source,bash]
----
make check
----

Package kbd:

[source,bash]
----
make DESTDIR=/usr/pkg/kbd-2.0.4 install
----

[NOTE]
====
For some languages (e.g., Belarusian) the Kbd package doesn't provide a useful keymap where the stock “by” keymap assumes the ISO-8859-5 encoding, and the CP1251 keymap is normally used. Users of such languages have to download working keymaps separately.
====

If desired, install the documentation:

[source,bash]
----
mkdir -pv           /usr/pkg/kbd-2.0.4/usr/share/doc/kbd
cp -R -v docs/doc/* /usr/pkg/kbd-2.0.4/usr/share/doc/kbd
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/kbd-2.0.4
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/kbd-2.0.4
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/kbd-2.0.4/* /
----

=== Libpipeline-1.5.0

Prepare Libpipeline for compilation:

[source,bash]
----
cd /var/tmp
tar -xf /sources/libpipeline-1.5.0.tar.gz
cd libpipeline-1.5.0
./configure --prefix=/usr
----

Compile the package:

[source,bash]
----
make
----

To test the results, issue:

[source,bash]
----
make check
----

Package libpipeline:

[source,bash]
----
make DESTDIR=/usr/pkg/libpipeline-1.5.0 install
----

Purging unneeded files:
[source,bash]
----
find /usr/pkg/libpipeline-1.5.0/usr/lib -name "*.la" -delete -printf "removed '%p'\n"
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/libpipeline-1.5.0
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/libpipeline-1.5.0
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/libpipeline-1.5.0/* /
----

Rebuild dynamic linker cache:
[source,bash]
----
ldconfig
----

=== Make-4.2.1
Extract source code:

[source,bash]
----
cd /var/tmp
tar -xf /sources/make-4.2.1.tar.bz2
cd make-4.2.1
----

Again, work around an error caused by glibc-2.27:

[source,bash]
----
sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c
----

Prepare Make for compilation:

[source,bash]
----
./configure --prefix=/usr
----

Compile the package:

[source,bash]
----
make
----

The test suite needs to know where supporting perl files are located. We use an environment variable to accomplish this. To test the results, issue:

[source,bash]
----
make PERL5LIB=$PWD/tests/ check
----

Package make:

[source,bash]
----
make DESTDIR=/usr/pkg/make-4.2.1 install
----

Purging unneeded files:
[source,bash]
----
rm -fv /usr/pkg/make-4.2.1/usr/share/info/dir
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/make-4.2.1
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/make-4.2.1
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/make-4.2.1/* /
----

=== Patch-2.7.6
Prepare Patch for compilation:

[source,bash]
----
cd /var/tmp
tar -xf /sources/patch-2.7.6.tar.xz
cd patch-2.7.6
./configure --prefix=/usr
----

Compile the package:

[source,bash]
----
make
----

To test the results, issue:

[source,bash]
----
make check
----

Package patch:

[source,bash]
----
make DESTDIR=/usr/pkg/patch-2.7.6 install
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/patch-2.7.6
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/patch-2.7.6
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/patch-2.7.6/* /
----

////
Purging unneeded files:
[source,bash]
----
存在する場合だけ
rm -fv /usr/pkg/PKG/usr/share/info/dir
rm -fv /usr/pkg/PKG/etc/ld.so.cache
find /usr/pkg/PKG/usr/{lib,lib32} -name "*.la" -delete -printf "removed '%p'\n"
find /usr/pkg/PKG \( -name ".packlist" -o -name "*.pod" \) -delete -printf "removed '%p'\n"
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/PKG
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/PKG
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/PKG/* /
----

ライブラリがインストールされたら (glibc以降)
Rebuild dynamic linker cache:
[source,bash]
----
ldconfig
----
////
