= Linux from Scratch
:source-highlighter: pygments
Kazutoshi Noguchi

== Installing Basic System Software
=== Gzip-1.9
Extract source code:
[source,bash]
----
cd /var/tmp
tar -xf /sources/gzip-1.9.tar.xz
cd gzip-1.9
----

Make some fixes required by glibc-2.28:

[source,bash]
----
sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
----


Prepare Gzip for compilation:

[source,bash]
----
./configure --prefix=/usr
----

Compile the package:

[source,bash]
----
make
----

To test the results, issue:

[source,bash]
----
make check
----

Two tests are known to fail in the LFS environment: help-version and zmore.

Package gzip:

[source,bash]
----
make DESTDIR=/usr/pkg/gzip-1.9 install
----

Purging unneeded files:
[source,bash]
----
rm -fv /usr/pkg/gzip-1.9/usr/share/info/dir
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/gzip-1.9
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/gzip-1.9
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/gzip-1.9/* /
----

=== IPRoute2-4.18.0
Extract source code:
[source,bash]
----
cd /var/tmp
tar -xf /sources/iproute2-4.18.0.tar.xz
cd iproute2-4.18.0
----

The `arpd` program included in this package will not be built since it is dependent on Berkeley DB, which is not installed in LFS. However, a directory for `arpd` and a man page will still be installed. Prevent this by running the commands below. If the `arpd` binary is needed, instructions for compiling Berkeley DB can be found in the BLFS Book at http://www.linuxfromscratch.org/blfs/view/8.3/server/databases.html#db.

[source,bash]
----
sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8
----

It is also necessary to disable building two modules that requires http://www.linuxfromscratch.org/blfs/view/8.3/postlfs/iptables.html.

[source,bash]
----
sed -i 's/.m_ipt.o//' tc/Makefile
----

Compile the package:

[source,bash]
----
make
----

This package does not have a working test suite.

Install the package:

[source,bash]
----
make DESTDIR=/usr/pkg/iproute2-4.18.0 install
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/iproute2-4.18.0
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/iproute2-4.18.0
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/iproute2-4.18.0/* /
----

////
Purging unneeded files:
[source,bash]
----
存在する場合だけ
rm -fv /usr/pkg/PKG/usr/share/info/dir
rm -fv /usr/pkg/PKG/etc/ld.so.cache
find /usr/pkg/PKG/usr/{lib,lib32} -name "*.la" -delete -printf "removed '%p'\n"
find /usr/pkg/PKG \( -name ".packlist" -o -name "*.pod" \) -delete -printf "removed '%p'\n"
----

Strip the debug information:
[source,bash]
----
strip-pkg /usr/pkg/PKG
----

Compress man and info pages:
[source,bash]
----
compressdoc /usr/pkg/PKG
----

Install the package:
[source,bash]
----
cp -rsv /usr/pkg/PKG/* /
----

ライブラリがインストールされたら (glibc以降)
Rebuild dynamic linker cache:
[source,bash]
----
ldconfig
----
////
